#!/usr/bin/with-contenv /bin/bash

source /assets/functions/00-container
prepare_service

sanity_db
db_ready mariadb
check_clamav
check_rabbitmq
check_spamassassin
configure_tls
configure_postal

if [[ $(mysql -h ${DB_HOST} -u${DB_USER} -p${DB_PASS} -s --skip-column-names -e "SELECT COUNT(DISTINCT table_name) FROM information_schema.columns WHERE table_schema = '"$DB_NAME"'") == 0 ]]; then
  print_warn "Detecting new Install. Initializing Database"
  if [ ! -n "$DB_ROOT_PASS" ]; then
    print_error "No Root Password Entered! You only need to provide the environment variable one time. Please try again."
    exit 1
  fi
  initialize_database
else
  silent /app/bin/postal upgrade
fi

chown -R postal: /app/
rm -rf /app/tmp/pids/*

liftoff
