#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service both single

PROCESS_NAME="fail2ban"
check_container_initialized
check_service_initialized init
liftoff

if [ "$FAIL2BAN_LOG_TYPE" = "FILE" ] ; then
    silent_arg="silent"
fi

sleep 180
print_info "Starting Fail2ban"
${silent_arg} fail2ban-server -f
