#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single

check_container_initialized
check_service_initialized init
liftoff

if var_false $LOG_CONSOLE ; then
    console="silent"
fi

print_info "Starting postal"
${console} /app/bin/postal start

while :
do
	/app/bin/postal status
	sleep 86400
done
