#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-postal-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-postal ]; then

        mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-postal
fi

echo ''
echo '** [postal] Starting postal'
exec /opt/postal/bin/postal run

