#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="postal"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting postal"
exec /opt/postal/bin/postal run
